### ISSUE TITLE
Is `CONTRIBUTORS.md` correct?

### ISSUE THREAD

**Issue by johenglisch** [SequenceComparison/starostinpie#1]
@LinguList `CONTRIBUTORS.md` lists you as an Author – the citation doesn't.  Should I change your entry in `CONTRIBUTORS.md` to Other?

https://github.com/SequenceComparison/starostinpie/blob/bad65c67fcadecdd99a29cb3e4bf187c93d5b705/CONTRIBUTORS.md#L5

**Comment by LinguList** [comment]
Yes, and please set Starostin as author then!
